/* eslint-disable */
// From Aug 2024, rewards are no longer stored in aavegotchi-contracts, instead they're generated by script
// Copy the relevant scripts here to generate the rewards and store in json file

// Run this with `node generateRewards.js`
// Move the generated rewards.json to the data/rf/szn9 folder
// This contains the rewards over the full season: configure fetchRfGotchis NUM_ROUNDS_REWARDS as '4'

const { readJsonFile, writeJsonFile } = require('../../fileUtils.js')
const fileName = "rewards.json"

// from scripts/airdrops/rarityfarming/szn9/rnd1.ts
const rarityParams = [750000.0, 7500, 0.94]
const kinshipParams = [300000.0, 7500, 0.76]
const xpParams = [150000.0, 7500, 0.65]
const totalAmount = 1200000

// Copy generateSeasonRewards from aavegotchi-contracts/scripts/generateRewards
function generateSeasonRewards(
  type,
  totalAmount,
  numWinners,
  y
) {
  const rewards = [];
  const k =
    totalAmount /
    Array.from({ length: numWinners }, (_, i) => 1 / Math.pow(i + 1, y)).reduce(
      (a, b) => a + b,
      0
    );

  console.log(type);

  for (let rank = 1; rank <= numWinners; rank++) {
    const reward = k / Math.pow(rank, y);

    rewards.push(Number(reward.toFixed(2)));
  }

  return rewards;
}

// from tasks/rarityPayouts.ts
async function generateRewards() {

    const rarityRoundRewards = generateSeasonRewards(
        "rarity",
        Number(rarityParams[0]), //total amount
        Number(rarityParams[1]), //num winners
        Number(rarityParams[2]) //y value
      );

      // check that the total amounts for the three leaderboards add up to the total amount for the round

      const individualRoundAmount =
        Number(rarityParams[0]) +
        Number(kinshipParams[0]) +
        Number(xpParams[0]);

      if (individualRoundAmount !== Number(totalAmount)) {
        throw new Error(
          "Total amount for the round does not match the sum of the individual leaderboard amounts"
        );
      }

      const kinshipRoundRewards = generateSeasonRewards(
        "kinship",
        Number(kinshipParams[0]), //total amount
        Number(kinshipParams[1]), //num winners
        Number(kinshipParams[2]) //y value
      );

      const xpRoundRewards = generateSeasonRewards(
        "xp",
        Number(xpParams[0]), //total amount
        Number(xpParams[1]), //num winners
        Number(xpParams[2]) //y value
      );

      await writeJsonFile(fileName, {
        rarity: rarityRoundRewards,
        kinship: kinshipRoundRewards,
        xp: xpRoundRewards
      })

      console.log("Rewards saved to " + fileName)
}

generateRewards()
